[package]
name = "test-generator"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
clap.workspace = true
anyhow.workspace = true
walkdir = "2.5.0"
chrono = "0.4.41"

[[bin]]
name = "test-generator"
path = "src/main.rs"