[package]
name = "expander"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
clap.workspace = true
anyhow.workspace = true

[[bin]]
name = "expander"
path = "src/main.rs"