name: CI

on:
  push:
    branches: [ main, add-ci-pipeline ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Pull pre-build CI Image
        run: docker pull ghcr.io/itsukiyoshida/cp-cplusplus/ci-env:latest

      - name: Run build/test matrix in container
        run: |
          docker run --rm -v itsukiyoshida/cp-cplusplus:/workspace -w /workspace \
          ghcr.io/itsukiyoshida/cp-cplusplus/ci-env:latest \
          bash -c '
            set -euo pipefail
            for preset in a b c d e f g h; do
              echo "::group::Configure ($preset)"
              cmake --preset "$preset"
              echo "::endgroup::"

              echo "::group::Build ($preset)"
              cmake --build --preset "$preset"
              echo "::endgroup::"

              echo "::group::Test ($preset)"
              ctest --preset "$preset" || exit 1
              echo "::endgroup::"
            done
          '
