name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Prepare test-results directory
        run: mkdir -p test-results

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Pull pre-build CI Image
        run: docker pull ghcr.io/itsukiyoshida/cp-cplusplus/ci-env:latest

      - name: Run build/test matrix in container
        run: |
          mkdir -p test-results
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -v ${{ github.workspace }}/test-results:/workspace/test-results \
            -w /workspace \
            ghcr.io/itsukiyoshida/cp-cplusplus/ci-env:latest \
            bash -c '
              set -euo pipefail
              (set +e; python3 make_test.py)
              for preset in a b c d e f g h; do
                echo "::group::Configure ($preset)"
                cmake --preset "$preset"
                echo "::endgroup::"

                echo "::group::Build ($preset)"
                cmake --build --preset "$preset"
                echo "::endgroup::"

                echo "::group::Test ($preset)"
                ctest --preset "$preset" --output-junit test-results/$preset.xml || true
                echo "::endgroup::"
              done
            '

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: CTest Results
          path: test-results/*.xml
          reporter: java-junit
          fail-on-error: false